### ISSUE TITLE
The stuff of nightmares.

### ISSUE THREAD

**Issue by Neltulz** [saschanaz/jxl-winthumb#6]
Tested in Windows Explorer and Directory Opus
OS: Windows 10 Pro 64bit
JXL-Winthumb version: v0.1.9
JXL version: 0.3.7
JXL settings used: ``"X:\ProgramFiles\JpegXL\cjxl.exe" {filepath} -d 2 -s 7 -j {filepath$|noext}_(JPEGXL_d2_s7).jxl``

Horrifying result:
![Clipboard Image](https://user-images.githubusercontent.com/7741742/124580995-47ca0200-de16-11eb-8560-d652d78370f0.jpg)

Expected result:
Well, definitely **NOT** what you see above on the right.

Original Image:
![IMG_20210704_184031 - Copy](https://user-images.githubusercontent.com/7741742/124580768-13eedc80-de16-11eb-9248-98701b2412e0.jpg)

Converted to JXL:
[IMG_20210704_184031 - Copy_(JPEGXL_d2_s7)_jxl.zip](https://github.com/saschanaz/jxl-winthumb/files/6769110/IMG_20210704_184031.-.Copy_.JPEGXL_d2_s7._jxl.zip)

**Comment by saschanaz** [comment]
Hmm, again this is Directory Opus specific issue as #1 was. I have no way to debug it since it's not open source, could you contact its devs instead?

**Comment by Neltulz** [comment]
> Hmm, again this is Directory Opus specific issue as #1 was. I have no way to debug it since it's not open source (and my trial is over and I don't really want to pay), could you contact its devs instead?

I tested it in Explorer as well.  The issue occurs in Explorer.

I made that clear in line 1.

**Comment by Neltulz** [comment]
![image](https://user-images.githubusercontent.com/7741742/124625320-4fec6680-de43-11eb-85fb-1ef2284f21ff.png)

As you can see, this issue is not limited to Directory Opus.

**Comment by saschanaz** [comment]
Thanks, but that doesn't seem the original File Explorer, what are you using and how can I make the preview size that big?

**Comment by Neltulz** [comment]
![image](https://user-images.githubusercontent.com/7741742/124625526-80340500-de43-11eb-81ac-5ed55c02ef1a.png)

**Comment by Neltulz** [comment]
> Thanks, but that doesn't seem like the original File Explorer, what are you using and how can I make the preview size that big?

![image](https://user-images.githubusercontent.com/7741742/124625687-a35eb480-de43-11eb-9eb6-b7595d44e0d9.png)

**Comment by saschanaz** [comment]
Hmm, still can't repro, but it could be a hardware dependent issue. I'll try updating libjxl, but before that, does it happen when the preview size is small?

**Comment by Neltulz** [comment]
![image](https://user-images.githubusercontent.com/7741742/124626219-16682b00-de44-11eb-9365-f7d7d0968f18.png)

**Comment by saschanaz** [comment]
Thanks again. Does it also happen if you copy-paste the file while the preview size is kept small? (I've seen File Explorer just reuses previous larger thumbnail when changing preview size. Copy-pasting makes sure it gets a new thumbnail.)

**Comment by Neltulz** [comment]
Just installed jxl-winthumb on my SECONDARY Ryzen PC.

Result:

![image](https://user-images.githubusercontent.com/7741742/124627151-ed946580-de44-11eb-8066-4eb6269e0635.png)

**Comment by Neltulz** [comment]
> Thanks again. Does it also happen if you copy-paste the file while the preview size is kept small? (I've seen File Explorer just reuses previous larger thumbnail when changing preview size. Copy-pasting makes sure it gets a new thumbnail.)

Considering, I just installed JXL-Winthumb on a secondary PC, that previously did not have JXL-Winthumb installed at all, I think it's safe to say that the issue lies with JXL-Winthumb, and not something about my computer hardware or computer software.

Also, I copied the images from my primary PC onto my secondary ryzen PC, into a completely separate folder, excluding the Thumbs.db file, so that Explorer would generate a new thumbnail image for the JXL.

**Comment by Neltulz** [comment]
Also, the hardware is about as different as they could possibly be.  My primary PC uses a core i7 6700k quad with an nvidia RTX 2070 super.  My secondary PC uses a ryzen 3700x with a dedicated AMD Radeon RX550 gpu.  The hardware is completely different.

**Comment by saschanaz** [comment]
I wanted to check whether the newly generated *small* thumbnail still has the same issue. By hardware-depedendent I mean a libjxl side bug (that could have been fixed in the latest version).

Anyway I'm doing libjxl update, I'll ping you when a new release happens.

**Comment by Neltulz** [comment]
> Thanks again. Does it also happen if you copy-paste the file while the preview size is kept small? (I've seen File Explorer just reuses previous larger thumbnail when changing preview size. Copy-pasting makes sure it gets a new thumbnail.)

![image](https://user-images.githubusercontent.com/7741742/124629204-d48cb400-de46-11eb-9bdd-ea7c92f60731.png)

I tried copying the images with Medium Icons, into a new folder, and it generated a new thumbnail for the JXL.  Still appears messed up.

Did I follow your instructions correctly?

**Comment by saschanaz** [comment]
Thank you for all the followups! I suspect it's a libjxl thing and hope the ongoing update fix your issue. (Will make it within an hour)

**Comment by Neltulz** [comment]
> Thank you for all the followups! I suspect it's a libjxl thing and hope the ongoing update fix your issue. (Will make it within an hour, unless something happens)

No problem, do not rush! :)  I will probably be asleep, so definitely relax, take your time.  Appreciate all of the hard work you're doing on this.

**Comment by saschanaz** [comment]
https://github.com/saschanaz/jxl-winthumb/releases/tag/v0.1.10

**Comment by Neltulz** [comment]
That appears to have fixed the issue! Thanks! :)

![image](https://user-images.githubusercontent.com/7741742/124675526-7087e100-de82-11eb-9954-4e3aeeeb6727.png)

**Comment by saschanaz** [comment]
Great! Closing as such 👍
